/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package recursion;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        // System.out.println(new App().getGreeting());

        // String Recursion Demo
        System.out.println("\n------------------- String Recursion -------------------");
        System.out.println("1. String Reversal");
        String input1 = "Hello";
        System.out.printf("The reversal of {%s} is {%s}.\n\n", input1, StringRecursion.reverseString(input1));

        System.out.println("2. Palindrome");
        String input2 = "racecar";
        System.out.printf("Is the string {%s} is a palindrom? {%b}\n\n", input2, StringRecursion.isPalindrome(input2));
    }
}
