/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package recursion;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.DisplayName;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @ParameterizedTest
    @ValueSource(strings = {"racecar", "kayak"})
    @DisplayName("Test isPalindrome recursive function")
    void isPalindromeTest(String input) {
        assertTrue(StringRecursion.isPalindrome(input));
    }

    @Test
    @DisplayName("Test DecimalToBinary recursive function")
    void DecimalToBinaryTest() {
        assertEquals("110", OtherRecursion.DecimalToBinary(6, ""));
    }
}
